#! /bin/bash
check()
{
	read
	cat /proc/devices
	read
	dmesg
	read
}
node()
{
	read -p "Please enter the major no:" major
	mknod cdev_A21988 c $major 0
	echo
	echo "Node is succesfuly made"
	echo
}
application()
{
	if ( make -C ./Application/ )
	then
		echo
		read -n1 -p "Do you want to make node (y/n):"
		if [ $REPLY == 'y' ]
		then
			echo
			node
			read -n1 -p "Do you want to run application(y/n):"
			if [ $REPLY == 'y' ]
			then
				echo
				./Application/Apps
			else
				echo
				echo "Application is not running"
			fi
		fi
		echo
	#	rm -rf ./Application/*.o
	fi
}
remove()
{
	rmmod Adesh
	check
	make clean
	rm -rf modules.order
	rm -rf Module.symvers
}
insert()
{
	insmod modules/Adesh.ko
	echo 
	lsmod
	check
	application
	read -n1 -p "Do you want to remove device (y/n):"
	if [ $REPLY == 'y' ]
	then 
		echo
		remove
	else
		echo "Adesh module is not removed"
		echo
	fi
}
if ( make )
then
	echo "make success..............."
	echo
	read -n1 -p "Do you want to insert device (y/n):"
	if [ $REPLY == 'y' ]
	then
		echo
		insert
	else
		echo
		echo "Bye have a nice day"
		echo
	fi
fi
